var body = document.body;
var secondSection = document.getElementById("second");
var toggle = document.querySelector(".toggle-icon");
var toggle2 = document.querySelector("#toggle-bar")
var toggle3 = document.querySelector(".toggle-icon-2");
 var stats = document.getElementById("statistics-bar");
 const para = document.querySelector(".p3",".p4");
 const para2 = document.querySelector(".post")
 const para3 = document.querySelector("#log");
 const para4 = document.querySelector(".p5");
 const para5 = document.querySelector(".p6");
 const para6 = document.querySelector(".p7");
 const para7 = document.querySelector(".p8");
 const para8 = document.querySelector(".p9",);
 const para10 = document.querySelector(".p10");
 const para9 = document.querySelector("#date");
 const para11 = document.querySelector(".p11");
 const para12 = document.querySelector(".p12");
 const para13 = document.querySelector(".p13")
 const add = document.querySelector("#add")
 const img = document.querySelector(".im");
 const img2 = document.querySelector(".im2");
 const img3 = document.querySelector(".im3")
 const img4 = document.querySelector(".im4")
 const btn = document.querySelector("#button");
 const icon1 = document.querySelector(".icon-1");
 const icon2 = document.querySelector(".icon-2");
 var dark = document.querySelector("#dark-mode");
 
 

toggle.addEventListener("click", function darkMode(){
    toggle2.style.background = "#0295A924"
    toggle3.style.display = "block"
    toggle3.style.background = "#0295A9"
    toggle.style.display = "none"
    body.style.backgroundColor = "black";
    body.style.color = "white";
    secondSection.style.backgroundColor = "#070609";
    stats.style.background = "black";
    dark.innerHTML = "Light mode"
    stats.style.color = "white";
    para.style.color = "white";
    para2.style.color = "white";
    para3.style.color = "white";
    para4.style.color = "white";
    para5.style.color = "white";
    para6.style.color = "white";
    para7.style.color = "white";
    para8.style.color = "white";
    para9.style.color = "white";
    para10.style.color = "white";
    para11.style.color = "white";
    para12.style.color = "white";
    para13.style.color = "white";
    add.style.color = 'white';
    img.style.filter = "invert(1) saturate(1) sepia(1) brightness(5) hue-rotate(0deg)"
    img2.style.filter = "invert(1) saturate(1) sepia(1) brightness(5) hue-rotate(0deg)"
    img3.style.filter = "invert(1) saturate(1) sepia(1) brightness(5) hue-rotate(0deg)"
    img4.style.filter = "invert(1) saturate(1) sepia(1) brightness(5) hue-rotate(0deg)";
    btn.style.borderColor = "white"
    btn.style.color = "white"
    icon1.style.borderColor = "white"
    icon2.style.borderColor = "white"
 })

 toggle3.addEventListener("click", function lightMode(){
    toggle2.style.background = "#0295A924"
    toggle3.style.display = "none"
    toggle3.style.background = "#0295A9"
    toggle.style.display = "block"
    body.style.backgroundColor = "white";
    body.style.color = "black";
    secondSection.style.backgroundColor = "#F8F8F8";
    dark.innerHTML = "Dark mode"
    stats.style.background = "white";
    stats.style.color = "initial";
    para.style.color = "initial";
    para2.style.color = "initial"
    para3.style.color = "initial";
    para4.style.color = "initial";
    para5.style.color = "initial";
    para6.style.color = "initial";
    para7.style.color = "initial";
    para8.style.color = "initial";
    para9.style.color = "initial";
    para10.style.color = "initial";
    para11.style.color = "initial";
    para12.style.color = "initial";
    para13.style.color = "initial";
    add.style.color = 'initial';
    img.style.filter = "none"
    img2.style.filter = "none"
    img3.style.filter = "none"
    img4.style.filter = "none";
    btn.style.borderColor = "black"
    btn.style.color = "black"
    icon1.style.borderColor = "black"
    icon2.style.borderColor = "black"
 })